name: Automation Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snickerbockers/submodules-init@v4

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11

      - run:
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
      - run:
          sudo apt install libtbb-dev

      - uses: actions/setup-python@v1

      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Db_coverage=true
          options: --verbose

      - run: |
          sudo apt install lcov
          mkdir coverage
          lcov -c -d . -o coverage/lcov.info
          lcov -r coverage/lcov.info "/usr*" "*test/lib/ut*" -o coverage/lcov.info

      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
