name: Automation Test

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: snickerbockers/submodules-init@v4

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 11

      - run:
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
      - run:
          sudo apt install libtbb-dev

      - uses: actions/setup-python@v1

      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Db_coverage=true
          options: --verbose

      - run: |
          pip install gcovr
          gcovr -e ".*ut\.hpp" --xml-pretty -o coverage.xml

      - uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
